version: '2'
services:
  app:
    image: 'activity-tracker-api:latest'
    build:
      context: .
    ports:
      - "8081:8080"
    container_name: activityApp
    depends_on:
      - activitytrackerDb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://activitytrackerDb:5433/ActivityTracker
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Orebela22
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  activitytrackerDb:
    image: 'postgres:latest'
    container_name: activitytrackerDb
    ports:
      - "5434:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Orebela22